# -*- mode: sh -*-
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# My Variables
#

# Make unzip quieter
export UNZIP="-q"

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='browser'
  export HOMEBREW_BROWSER=$BROWSER
fi

# Read homebrew's API token
if [[ "$OSTYPE" == darwin* ]]; then
  export HOMEBREW_GITHUB_API_TOKEN=$(cat $HOME/.zsh.secret )
fi


#
# Editors
#

if [[ "$OSTYPE" == darwin* ]]; then
  export EDITOR='emacsclient'
else
  export EDITOR='vim'
fi

export VISUAL=$EDITOR
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
if [[ "$OSTYPE" == darwin* ]]; then
  path=(
    # Duplicate the rbenv & pyenv path so they could work in Emacs
    $HOME/.rbenv/{bin,shims}
    $HOME/.pyenv/{bin,shims}
    $HOME/Code/bin
    $HOME/.zprezto/bin
    /usr/local/{bin,sbin}
    $path
  )
else
  path=(
    $path
  )
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -R -S -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Hunspell
#

if [[ "$OSTYPE" == darwin* ]]; then
  export DICPATH="/Users/Bx7/Library/Spelling"
fi

#
# Yarn
#

if (( $+commands[yarn] )); then
  path+=$(yarn global bin)
fi


#
# Go
#
if (( $+commands[go] )); then
  export GOPATH="$HOME/Code/go/"
  path+=( $HOME/Code/go/bin )
fi

#
# SQLite
#
path=(
  "/usr/local/opt/sqlite/bin"
  $path
)

#
# bat
#
if (( $+commands[bat] )); then
  export BAT_THEME="zenburn"
  alias cat="bat --style=plain"
fi

#
# jump - fasd replacement
#
if (( $+commands[jump] )); then
  eval "$(jump shell)"
fi

#
# GNU units
#
if (( $+commands[gunits] )); then
  path=(
    "/usr/local/opt/gnu-units/libexec/gnubin"
    $path
  )
fi
